### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by george0884** [brute4s99/knotifications#2]
My windows version is       Versión	10.0.18362 compilación 18362

It installs but does not run

**Comment by tm9k1** [comment]
Hi @george0884 !
it seems you posted the issue at the wrong repository
https://github.com/brute4s99/kdeconnect-kde is the right one. 

I may be wrong, please confirm anyway. :)

**Comment by george0884** [comment]
Yes my mistake, sorry.

**Comment by tm9k1** [comment]
okay, closing this issue now. See you at the new issue!
